package provider

import "strings"

// knownIndexAliases maps colloquial or partial index names to their canonical names
// or tsCodes that exist in the tushare index_basic table.
//
// This handles cases where the user's query (e.g. "中证消费") does not match
// any index name exactly but corresponds to a known broad-market index.
//
// Key insight: SZ/SH indices in index_basic store the tsCode itself as the name
// field (e.g. "000300.SZ" for 沪深300), not the standard Chinese name. There is
// no programmatic way to derive "沪深300" → "000300.SZ" without this table.
//
// Generated by: scripts/refresh_index_aliases.py
// Enriched with: 同花顺/10jqka quant 常用股票型指数列表 (https://quant.10jqka.com.cn) + tushare index_basic 验证
// To update, run: make refresh-index-aliases
var knownIndexAliases = map[string]string{
	// === 宽基 ===
	"沪深300":      "000300.SH",  // 注: .CSI 只有 20 天，用 .SH 获取完整历史
	"中证500":      "000905.SH",  // 同上
	"中证1000":     "000852.SH",  // 同上
	"中证红利":     "000922.CSI",  // .SH 无数据，.CSI 有完整历史
	"红利低波":     "h30269.CSI",  // 红利低波净收益；.SH 无数据，h30269 有完整历史
	"红利指数":     "000015.SH",  // 上证红利指数（000922 是中证红利）
	"创业板指":     "399006.SZ",
	"创业板50":     "399673.SZ",
	"科创50":       "000688.SH",
	"科创100":      "000689.CSI",
	"上证50":       "000016.SH",
	"上证指数":     "000001.SH",
	"深证成指":     "399001.SZ",
	"北证50":       "899050.BJ",
	"基本面50":     "000925.CSI",  // 中证基本面 50
	"中证A股":      "930903.CSI",  // 中证 A 股指数
	// === 红利/低波 ===
	"300红利":      "000821.CSI",
	"中证红利质量": "932315.CSI",
	// === 消费 ===
	"中证消费":     "399932.SZ",
	"全指消费":     "000990.CSI",
	"主要消费":     "000932.CSI",
	"可选消费":     "000989.CSI",
	"消费服务":     "000806.CSI",
	// === 医药 ===
	"中证医药":     "000933.SH",   // 注: .CSI 只有 20 天，用 .SH 获取完整历史
	"全指医药":     "000991.CSI",
	"300医药":      "000913.CSI",
	"中证医疗":     "399395.SZ",
	// === 金融 ===
	"中证银行":     "399986.SZ",
	"300银行":      "000951.CSI",
	"中证证券":     "399975.SZ",
	"中证保险":     "399809.SZ",
	// === 科技/制造 ===
	"中证军工":     "399967.SZ",
	"中证电子":     "930652.CSI",
	"中证半导体":   "931087.CSI",
	"中证计算机":   "000986.CSI",
	"中证通信":     "000993.CSI",
	"中证汽车":     "930607.CSI",
	"中证钢铁":     "930606.CSI",
	// === 能源/原材料 ===
	"中证煤炭":     "399998.SZ",
	"中证有色金属": "000819.CSI",
	"中证能源":     "000928.CSI",
	// === 消费细分 ===
	"中证白酒":     "399997.SZ",
	"中证食品饮料": "000396.CSI",
	// === 房地产/基建 ===
	"中证房地产":   "399393.SZ",
	"中证基建":     "399965.SZ",
	"中证建筑材料": "399995.SZ",
	// === 风格 ===
	"中证价值":     "000920.CSI",
	"中证成长":     "000921.CSI",
	"300价值":      "000919.CSI",
	"300成长":      "000918.CSI",
	"500价值":      "000515.CSI",
	"500成长":      "000516.CSI",
	"1000价值":     "000062.CSI",
	"1000成长":     "000063.CSI",
	// === 债券 ===
	// === 其他 ===
	"中证新能源":   "000941.CSI",
	// "中证家电":   // 无对应 index_basic 条目；tushare 中 000903 = 中证A100
	"中证传媒":     "000971.CSI",
	"中证农林牧渔": "000949.CSI",
	"中证电力设备": "931932.CSI",
	// === 港股/海外（^前缀 = tushare index_global API）===
	"恒生指数":    "^HSI",        // Hang Seng Index（tushare name 为英文，无中文别名）
	"恒生科技":    "^HSTECH",     // Hang Seng TECH Index（tushare name 为英文）
	// === 港股通（A-H 轮动分析用，tushare 93xxx 系列，CNY 计价）===
	"港股通科技":   "931573",      // 港股通科技（不含 HKD 汇率转换）
	"港股通消费":   "930964",      // 港股通消费 C（不含 HKD 汇率转换）
	"港股通医疗":   "931966",      // 港股通医疗商业（不含 HKD 汇率转换）
	"港股通金融":   "930966",      // 港股通金融 C（不含 HKD 汇率转换）
	"港股通能源":   "930960",      // 港股通能源 C（不含 HKD 汇率转换）
	"港股通地产":   "931025",      // 港股通地产（不含 HKD 汇率转换）
}

func resolveKnownIndexAlias(query string) (string, bool) {
	alias := strings.ToLower(strings.TrimSpace(query))
	if canonical, ok := knownIndexAliases[alias]; ok {
		return canonical, true
	}
	return "", false
}

func filterTushareAssets(rows []tushareRow, query string, market string, assetClass string, exactMatch bool) []Asset {
	assets := []Asset{}
	queryLower := strings.ToLower(strings.TrimSpace(query))
	for _, row := range rows {
		tsCode := row.string("ts_code")
		name := row.string("name")
		if queryLower != "" && !matchesTushareAssetQuery(tsCode, name, queryLower, exactMatch) {
			continue
		}
		assetMarket := marketFromTushareCode(tsCode)
		if !marketMatches(assetMarket, market) {
			continue
		}
		exchange := row.string("exchange")
		if exchange == "" {
			exchange = exchangeFromTushareCode(tsCode)
		}
		assets = append(assets, Asset{Symbol: publicSymbolFromTushareCode(tsCode), Name: name, Market: assetMarket, AssetClass: assetClass, Currency: currencyForMarket(assetMarket), Exchange: exchange, Source: tushareSource, Metadata: map[string]any{"provider": tushareSource, "tsCode": tsCode, "tsCodeAsset": inferTushareAssetType(tsCode)}})
	}
	return assets
}

func matchesTushareAssetQuery(tsCode string, name string, queryLower string, exactMatch bool) bool {
	if queryLower == "" {
		return true
	}
	// exactMatch: only accept if name equals query (case-insensitive)
	if exactMatch {
		if strings.EqualFold(name, queryLower) {
			return true
		}
		// Also check aliases for tsCode formats
		for _, candidate := range tushareSearchAliases(tsCode) {
			if strings.EqualFold(candidate, queryLower) {
				return true
			}
		}
		return false
	}
	// Substring match (existing behavior)
	for _, candidate := range tushareSearchAliases(tsCode) {
		if strings.Contains(candidate, queryLower) {
			return true
		}
	}
	return strings.Contains(strings.ToLower(name), queryLower)
}

func tushareSearchAliases(tsCode string) []string {
	aliases := []string{}
	pushAlias := func(value string) {
		value = strings.ToLower(strings.TrimSpace(value))
		if value == "" {
			return
		}
		for _, existing := range aliases {
			if existing == value {
				return
			}
		}
		aliases = append(aliases, value)
	}
	publicSymbol := publicSymbolFromTushareCode(tsCode)
	pushAlias(tsCode)
	pushAlias(publicSymbol)
	if publicSymbol != "" {
		pushAlias(publicSymbol + ".SH")
		pushAlias(publicSymbol + ".SZ")
		pushAlias(publicSymbol + ".CSI")
	}
	return aliases
}

func inferTushareAsset(query string) (Asset, bool) {
	queryUpper := strings.ToUpper(strings.TrimSpace(query))
	// ^-prefixed global indices (e.g. "^HSTECH")
	if strings.HasPrefix(queryUpper, "^") {
		upper := strings.TrimPrefix(queryUpper, "^")
		var tsCode, name string
		switch upper {
		case "HSTECH", "HKTECH":
			tsCode, name = "HKTECH", "Hang Seng TECH Index"
		case "HSI":
			tsCode, name = "HSI", "Hang Seng Index"
		default:
			return Asset{}, false
		}
		return Asset{
			Symbol:     "^" + upper,
			Name:      name,
			Market:    "HK",
			AssetClass: "index",
			Currency:  "HKD",
			Exchange:  "HKEX",
			Source:    tushareSource,
			Metadata:  map[string]any{"provider": tushareSource, "tsCode": tsCode, "tsCodeAsset": "I"},
		}, true
	}
	// If query uses .CSI tsCode suffix, treat it as index regardless of numeric code
	// This handles cases like "000922.CSI" which would otherwise be resolved as equity
	if strings.HasSuffix(queryUpper, ".CSI") {
		return Asset{
			Symbol:     queryUpper,
			Name:      queryUpper,
			Market:    "A",
			AssetClass: "index",
			Currency:  "CNY",
			Exchange:  "CSI",
			Source:    tushareSource,
			Metadata:  map[string]any{"provider": tushareSource, "tsCode": queryUpper, "tsCodeAsset": "I"},
		}, true
	}
	// .SZ/.SH/.BJ suffix also indicates a specific A-market tsCode
	if strings.HasSuffix(queryUpper, ".SZ") || strings.HasSuffix(queryUpper, ".SH") || strings.HasSuffix(queryUpper, ".BJ") {
		exchange := "SZ"
		if strings.HasSuffix(queryUpper, ".SH") {
			exchange = "SH"
		} else if strings.HasSuffix(queryUpper, ".BJ") {
			exchange = "BJ"
		}
		assetType := inferTushareAssetType(queryUpper)
		assetClass := "equity"
		if assetType == "FD" {
			assetClass = "fund"
		} else if assetType == "I" {
			assetClass = "index"
		}
		return Asset{
			Symbol:     queryUpper,
			Name:      queryUpper,
			Market:    "A",
			AssetClass: assetClass,
			Currency:  "CNY",
			Exchange:  exchange,
			Source:    tushareSource,
			Metadata:  map[string]any{"provider": tushareSource, "tsCode": queryUpper, "tsCodeAsset": assetType},
		}, true
	}
	tsCode := normalizeTushareCode(query)
	if tsCode == "" {
		return Asset{}, false
	}
	assetMarket := marketFromTushareCode(tsCode)
	assetType := inferTushareAssetType(tsCode)
	assetClass := "equity"
	if assetType == "FD" {
		assetClass = "fund"
	} else if assetType == "I" {
		assetClass = "index"
	}
	name := tsCode
	if strings.HasPrefix(tsCode, "510300") {
		name = "沪深300ETF"
	}
	return Asset{Symbol: publicSymbolFromTushareCode(tsCode), Name: name, Market: assetMarket, AssetClass: assetClass, Currency: currencyForMarket(assetMarket), Exchange: exchangeFromTushareCode(tsCode), Source: tushareSource, Metadata: map[string]any{"provider": tushareSource, "tsCode": tsCode, "tsCodeAsset": assetType}}, true
}

func inferTushareGlobalIndex(query string) (Asset, bool) {
	tsCode := normalizeTushareGlobalIndexCode(query)
	if tsCode == "" {
		return Asset{}, false
	}
	name := tsCode
	symbol := tsCode
	if tsCode == "HSI" {
		name = "Hang Seng Index"
		symbol = "^HSI"
	}
	if tsCode == "HKTECH" {
		name = "Hang Seng TECH Index"
		symbol = "^HSTECH"
	}
	return Asset{Symbol: symbol, Name: name, Market: "HK", AssetClass: "index", Currency: "HKD", Exchange: "HKEX", Source: tushareSource, Metadata: map[string]any{"provider": tushareSource, "tsCode": tsCode, "tsCodeAsset": "I"}}, true
}

func inferTushareOpenFund(query string, market string) (Asset, bool) {
	tsCode := normalizeOpenFundCode(query, market)
	if tsCode == "" {
		return Asset{}, false
	}
	return Asset{Symbol: strings.TrimSuffix(tsCode, ".OF"), Name: tsCode, Market: normalizeMarket(market), AssetClass: "fixed_income", Currency: "CNY", Exchange: "OF", Source: tushareSource, Metadata: map[string]any{"provider": tushareSource, "tsCode": tsCode, "tsCodeAsset": "FD"}}, true
}

func normalizeTushareCode(symbol string) string {
	symbol = strings.ToUpper(strings.TrimSpace(symbol))
	symbol = strings.TrimPrefix(symbol, "SH")
	symbol = strings.TrimPrefix(symbol, "SZ")
	symbol = strings.ReplaceAll(symbol, ".SS", ".SH")
	if code := normalizeSixDigit(symbol); strings.HasPrefix(code, "93") {
		return code + ".CSI"
	}
	if strings.HasSuffix(symbol, ".SH") || strings.HasSuffix(symbol, ".SZ") || strings.HasSuffix(symbol, ".CSI") {
		return symbol
	}
	code := normalizeSixDigit(symbol)
	if code == "" {
		return ""
	}
	if strings.HasPrefix(code, "93") {
		return code + ".CSI"
	}
	if strings.HasPrefix(code, "5") || strings.HasPrefix(code, "6") || strings.HasPrefix(code, "9") {
		return code + ".SH"
	}
	return code + ".SZ"
}

func normalizeTushareGlobalIndexCode(symbol string) string {
	upper := strings.ToUpper(strings.TrimSpace(symbol))
	upper = strings.TrimPrefix(upper, "^")
	switch upper {
	case "HSI":
		return "HSI"
	case "HSTECH", "HKTECH":
		return "HKTECH"
	}
	return ""
}

func normalizeOpenFundCode(symbol string, market string) string {
	upper := strings.ToUpper(strings.TrimSpace(symbol))
	if strings.HasSuffix(upper, ".OF") {
		code := strings.TrimSuffix(upper, ".OF")
		if normalizeSixDigit(code) != "" {
			return code + ".OF"
		}
		return ""
	}
	if normalizeMarket(market) != "BOND" {
		return ""
	}
	code := normalizeSixDigit(upper)
	if code == "" {
		return ""
	}
	return code + ".OF"
}

func isFuturesMainSymbol(symbol string) bool {
	return normalizeFuturesMappingCode(symbol) != ""
}

func normalizeFuturesMappingCode(symbol string) string {
	upper := strings.ToUpper(strings.TrimSpace(symbol))
	if strings.Contains(upper, ".") {
		parts := strings.SplitN(upper, ".", 2)
		if parts[0] != "" && futuresExchangeFor(parts[0]) != "" {
			return upper
		}
	}
	underlying := strings.TrimRight(upper, "0123456789")
	if underlying == "" || underlying == upper {
		return ""
	}
	exchange := futuresExchangeFor(underlying)
	if exchange == "" {
		return ""
	}
	return underlying + "." + exchange
}

func futuresExchangeFor(underlying string) string {
	switch strings.ToUpper(strings.TrimSpace(underlying)) {
	case "AD", "AG", "AL", "AO", "AU", "BR", "BU", "CU", "FU", "HC", "NI", "OP", "PB", "RB", "RU", "SN", "SP", "SS", "WR", "ZN":
		return "SHF"
	case "BC", "EC", "LU", "NR", "SC":
		return "INE"
	case "AP", "CF", "CJ", "CY", "FG", "MA", "OI", "PF", "PK", "PL", "PR", "PX", "RM", "RS", "SA", "SF", "SH", "SM", "SR", "TA", "UR":
		return "ZCE"
	case "A", "B", "BB", "BZ", "C", "CS", "EB", "EG", "FB", "I", "J", "JD", "JM", "L", "LG", "LH", "M", "P", "PG", "PP", "RR", "V", "Y":
		return "DCE"
	case "IC", "IF", "IH", "IM", "T", "TF", "TL", "TS":
		return "CFX"
	case "LC", "PD", "PS", "PT", "SI":
		return "GFE"
	}
	return ""
}

func normalizeSixDigit(symbol string) string {
	symbol = strings.ToUpper(strings.TrimSpace(symbol))
	if strings.Contains(symbol, ".") {
		symbol = strings.Split(symbol, ".")[0]
	}
	if len(symbol) == 6 && isDigits(symbol) {
		return symbol
	}
	return ""
}

func inferTushareAssetType(tsCode string) string {
	// .CSI/.SZ/.SH/.BJ suffix always means index, regardless of numeric code
	if strings.HasSuffix(tsCode, ".CSI") || strings.HasSuffix(tsCode, ".SZ") || strings.HasSuffix(tsCode, ".SH") || strings.HasSuffix(tsCode, ".BJ") {
		return "I"
	}
	code := normalizeSixDigit(tsCode)
	if code == "" {
		return "E"
	}
	for _, prefix := range []string{"15", "16", "50", "51", "52", "56", "58"} {
		if strings.HasPrefix(code, prefix) {
			return "FD"
		}
	}
	// Below checks are now covered by the suffix check above, kept for clarity
	if strings.HasPrefix(tsCode, "000") && strings.HasSuffix(tsCode, ".SH") {
		return "I"
	}
	if strings.HasPrefix(tsCode, "399") && strings.HasSuffix(tsCode, ".SZ") {
		return "I"
	}
	return "E"
}

func isSixDigitSymbol(symbol string) bool {
	return normalizeSixDigit(symbol) != ""
}

func isDigits(value string) bool {
	for _, char := range value {
		if char < '0' || char > '9' {
			return false
		}
	}
	return value != ""
}

func marketFromTushareCode(tsCode string) string {
	upper := strings.ToUpper(tsCode)
	if strings.HasSuffix(upper, ".SH") || strings.HasSuffix(upper, ".SZ") || strings.HasSuffix(upper, ".CSI") {
		return "A"
	}
	return "US"
}

func exchangeFromTushareCode(tsCode string) string {
	upper := strings.ToUpper(tsCode)
	if strings.HasSuffix(upper, ".CSI") {
		return "CSI"
	}
	if strings.HasSuffix(upper, ".SH") {
		return "SSE"
	}
	if strings.HasSuffix(upper, ".SZ") {
		return "SZSE"
	}
	return ""
}

func publicSymbolFromTushareCode(tsCode string) string {
	return strings.TrimSuffix(strings.TrimSuffix(strings.TrimSuffix(tsCode, ".CSI"), ".SH"), ".SZ")
}

func marketFromYahooSymbol(symbol string) string {
	symbol = strings.ToUpper(symbol)
	if strings.HasSuffix(symbol, ".HK") {
		return "HK"
	}
	if strings.HasSuffix(symbol, ".SS") || strings.HasSuffix(symbol, ".SZ") {
		return "A"
	}
	return "US"
}

func marketMatches(actual string, requested string) bool {
	requested = strings.ToUpper(strings.TrimSpace(requested))
	return requested == "" || requested == "ALL" || strings.ToUpper(actual) == requested
}

func currencyForMarket(market string) string {
	switch strings.ToUpper(market) {
	case "A":
		return "CNY"
	case "HK":
		return "HKD"
	default:
		return "USD"
	}
}

func eastmoneySecID(code string, symbol string) string {
	upper := strings.ToUpper(symbol)
	// SH-market: .SH, .CSI, .SS (CSI index notation), or codes starting with 5/6/9
	if strings.Contains(upper, ".SH") || strings.Contains(upper, ".CSI") || strings.Contains(upper, ".SS") || strings.HasPrefix(code, "5") || strings.HasPrefix(code, "6") || strings.HasPrefix(code, "9") {
		return "1." + code
	}
	return "0." + code
}

func normalizeYahooSymbol(symbol string, market string) string {
	symbol = strings.ToUpper(strings.TrimSpace(symbol))
	if strings.Contains(symbol, "=X") || strings.Contains(symbol, ".") {
		return symbol
	}
	if normalizeMarket(market) == "HK" && isDigits(symbol) {
		return strings.TrimLeft(symbol, "0") + ".HK"
	}
	if normalizeMarket(market) == "A" && isSixDigitSymbol(symbol) {
		if strings.HasPrefix(symbol, "5") || strings.HasPrefix(symbol, "6") || strings.HasPrefix(symbol, "9") {
			return symbol + ".SS"
		}
		return symbol + ".SZ"
	}
	return symbol
}
